### ISSUE TITLE
🚑 HOTFIX. 시장페이지 반응형 수정

### ISSUE THREAD

**Issue by sengooooo** [2024-4lineton/Frontend#8]
# 📝 Preview
개망햇ㅇ어요..
![image](https://github.com/user-attachments/assets/96d03c95-4a34-4b90-a2dd-4c217dd16cd1)

# ✅ Todo
- [x] 반응형 수정
- [ ]
- [ ]

# 📌 Remark

**Comment by sengooooo** [comment]
도와주세요•••
![image](https://github.com/user-attachments/assets/5e51540b-e085-4e40-8d77-30bbf39eea7e)

**Comment by sengooooo** [comment]
![image](https://github.com/user-attachments/assets/d30863b2-4f46-42c0-af7d-1635b91fcc28)

**Comment by s0obang** [comment]
ㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋ
락스.온더락으로..........
